### ISSUE TITLE
type property 'all-content'

### ISSUE THREAD

**Issue by EnDe** [OWASP/owasp-summits#103]
some pages contain the property <type: all-content> but the usage in _layouts/all-content.html checks for <content>

Is this intended behaviour?

**Comment by DinisCruz** [comment]
that is legacy and can be removed

I just added this to the [Summit Website](https://github.com/OWASP/owasp-summit-2017/projects/1) project ToDo list

![image](https://cloud.githubusercontent.com/assets/656739/23579815/670fbc50-00ed-11e7-8b32-3995f4ff63a2.png)

**Comment by DinisCruz** [comment]
I think that on the latest refactoring this has been fixed (just need to double check)
