### ISSUE TITLE
Create FAQ page to capture tech equipment available at the Summit

### ISSUE THREAD

**Issue by DinisCruz** [OWASP/owasp-summits#1052]
This includes 

 - Items to buy from Amazon on next purchase event (link to Amazon Summit list)
 - items purchased and on route
 - items provided by participants (for example I will bring a camera and tripod)

For example capture info like this
![image](https://user-images.githubusercontent.com/656739/26925508-f2c0ccae-4c41-11e7-85e2-536df4f2d585.png)

**Comment by jemmads** [comment]
Project set up, needs to be populated

**Comment by jemmads** [comment]
https://github.com/OWASP/owasp-summit-2017/projects/7
