### ISSUE TITLE
Sort registration table

### ISSUE THREAD

**Issue by DinisCruz** [OWASP/owasp-summits#1053]
![image](https://user-images.githubusercontent.com/656739/26927488-f2ba7798-4c49-11e7-9e50-b86af53cb624.png)

**Comment by jemmads** [comment]
Have name badges been sourced at this point?

**Comment by jemmads** [comment]
Unable to order from Amazon for delivery on time. A road trip needs to be arranged to head out to Staples/Office Outlet in Milton Keynes. URGENT TASK.
