### ISSUE TITLE
Bag printing for delivery on Saturday

### ISSUE THREAD

**Issue by jemmads** [OWASP/owasp-summits#1059]
Bag proof to be approved

**Comment by jemmads** [comment]
[OWASP_2017_PROOF.pdf](https://github.com/OWASP/owasp-summit-2017/files/1061379/OWASP_2017_PROOF.pdf)

**Comment by jemmads** [comment]
Payment required asap
[Surcharge Pro Forma Order Confirmation.pdf](https://github.com/OWASP/owasp-summit-2017/files/1061635/Surcharge.Pro.Forma.Order.Confirmation.pdf)
[CLEVERBAGTERMS.pdf](https://github.com/OWASP/owasp-summit-2017/files/1061636/CLEVERBAGTERMS.pdf)
[MAKING A PAYMENT.pdf](https://github.com/OWASP/owasp-summit-2017/files/1061637/MAKING.A.PAYMENT.pdf)

**Comment by jemmads** [comment]
Text confirmation of delivery on 10 June

**Comment by SebaDele** [comment]
delivered
