### ISSUE TITLE
obtain and install SSL certificate

### ISSUE THREAD

**Issue by FrancoisRaynaud** [OWASP/owasp-summits#116]
Important since we should be running the main site with SSL

**Comment by DinisCruz** [comment]
This will be a challenge since I don't think GH supports SSL for custom domains https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it

**Comment by DinisCruz** [comment]
This could be done as part of the CI integration (see #184)

**Comment by fzipi** [comment]
This can be closed now.
