### ISSUE TITLE
create list of owasp leaders

### ISSUE THREAD

**Issue by SebaDele** [OWASP/owasp-summits#117]
for all the project/chapter leaders: compile a list of names together with email address in spreadsheet. will then be used to do a mailing

**Comment by devbh** [comment]
Current update:  updated LATAM, US, Australia, Canada. Working on EU

**Comment by NikitaOwasp** [comment]
Updated UK, Switzerland, Italy, Ireland, Sweden, Turkey, Spain, France, Belgium, Denmark, Poland, Finland, Germany, etc.
