### ISSUE TITLE
Multi-track sessions show multiple times on personal schedule

### ISSUE THREAD

**Issue by bkimminich** [OWASP/owasp-summits#1206]
## This...
![image](https://user-images.githubusercontent.com/3531020/27010344-a1b25cfc-4ea2-11e7-938e-f014fe4faada.png)
## ...leads to this
![image](https://user-images.githubusercontent.com/3531020/27010341-945d60ec-4ea2-11e7-81e5-e1665fe6fe24.png)

**Comment by fzipi** [comment]
This happens because session is listed in two different tracks:

track        : Threat Model,Juice Shop

**Comment by bkimminich** [comment]
I know. But can it be fixed? 😇

Am 12. Juni 2017 00:15:34 MESZ schrieb "Felipe Zipitría" <notifications@github.com>:

**Comment by DinisCruz** [comment]
I just fixed this, can you double check?

![image](https://user-images.githubusercontent.com/656739/27070333-779d0af6-5010-11e7-9f7f-4d5d7ff27c0b.png)
