### ISSUE TITLE
Make changes to the participants page and align it. 

### ISSUE THREAD

**Issue by devbh** [OWASP/owasp-summits#122]
Fixes to make to https://github.com/OWASP/owasp-summit-2017/pull/121/files
- [x]  The image should just be the url
- [x] the linkedIn should just be the name
- [x] the twitter should not have the @
- [x] There is no need to have the name on line 12 (since that is shown on the site from the 'title' field)

**Comment by DinisCruz** [comment]
Hi @devbh @NikitaOwasp 

It is better to split issues (for example this one has two separate tasks)

Specially since I believe you already did the first one (see the use of GitHub Checkboxes above, ,which is pretty cool)

**Comment by NikitaOwasp** [comment]
Hi @DinisCruz, yes the checkboxes seem pretty convenient. (checked them all since I have made all changes for Danny Grander's file)

**Comment by DinisCruz** [comment]
@NikitaOwasp so in this case it is better to remove the 'Create a template for new participants ' from this issue, close it, and then create a new issue just called 'Create a template for new participants ' (where we can track the ideas for that change)

**Comment by NikitaOwasp** [comment]
Hi @DinisCruz I'll separate the two but I'm not closing this as the alignment has not been corrected for all participants. Plus, not everyone has added their details. I can send them reminders once the shared spreadsheet is populated with participants' email addresses.

**Comment by DinisCruz** [comment]
Hi @NikitaOwasp can you look at the new Participant(s) pages and update this issue?

thx

**Comment by NikitaOwasp** [comment]
Hi @DinisCruz, I looked at the new pages and made some changes (according to the guidelines above) but they're not reflecting with the new design. Please advise.

For e.g. I updated -- http://owaspsummit.org/Participants/Alexander-Antukh.html 
The changes are showing in GitHub -- https://github.com/NikitaOwasp/owasp-summit-2017/pull/2/commits/b7fe126dad3c2a91c1b8d9ae44a180b454126e1b 
But on the main page, the changes are not reflecting.

**Comment by DinisCruz** [comment]
Hi, you need to send those changes as Pull Requests to the main repo

like this

![image](https://cloud.githubusercontent.com/assets/656739/24832970/3c382174-1cb4-11e7-8010-6fbf34ea5773.png)

![image](https://cloud.githubusercontent.com/assets/656739/24832972/48d3479c-1cb4-11e7-9502-d95f22d0ce52.png)

which I can then merge

![image](https://cloud.githubusercontent.com/assets/656739/24832977/55d582d4-1cb4-11e7-8341-55b007a5e374.png)

![image](https://cloud.githubusercontent.com/assets/656739/24832980/622aec72-1cb4-11e7-91ae-8a8377dab7b8.png)

**Comment by DinisCruz** [comment]
Those changes are live now

http://owaspsummit.org/Participants/Alexander-Antukh.html

http://owaspsummit.org/Participants/Daniel-Kefer.html

**Comment by NikitaOwasp** [comment]
Hi @DinisCruz,
The tags which we earlier discussed are not working with the new design. ( the linkedIn should just be the name, the twitter should not have the @, There is no need to have the name on line 12 (since that is shown on the site from the 'title' field) 
So, the updated page for say, Alexander Antukh, is not showing his linkedin, twitter handles even though they are there in Github. Please let me know what's our new style on this now, thanks.

**Comment by DinisCruz** [comment]
Hi @NikitaOwasp can you check now?

the design is not the best one, but the values should show in the participant's page

![image](https://cloud.githubusercontent.com/assets/656739/24876879/38a5698c-1e25-11e7-87c8-96b15ee6a219.png)

**Comment by NikitaOwasp** [comment]
Hi @DinisCruz, 
Yes, it's showing up now.
