### ISSUE TITLE
Upvoting mechanism for working sessions

### ISSUE THREAD

**Issue by bkimminich** [OWASP/owasp-summits#127]
**As a** visitor of the OWASP Summit website
**I want** to be able to upvote my favorite working sessions
**so that** the summit participants will focus on the demands of the community
**and** spend their time and effort on topics will the highest potential value.

**Comment by DinisCruz** [comment]
yeah, great idea, the question now is how?

One way I was thinking of allowing users to sign up to Working Sessions was via their participant's page (maybe using a property). But that will not be friction free.

On the other hand that will solve all sorts of issues (to do with Auth and Authz)

**Comment by bkimminich** [comment]
This issue became obsolete in a way when we introduced the `participants` property. Although that is way less convenient to use, it serves the purpose.
