### ISSUE TITLE
Key reallocation

### ISSUE THREAD

**Issue by jemmads** [OWASP/owasp-summits#1389]
Find a solution for the keys. What is the process for reallocating keys from those who have checked out to those who are arriving later in the week?

My suggestion is a buddy system, one person from each villa takes responsibility for introducing the newcomer to their home for the week. This should be added to the room allocation page and linked to the buddy's profile and schedule.

Do you think this is agreeable?

**Comment by fzipi** [comment]
No more keys to share, we are leaving!
