### ISSUE TITLE
Only commit using GPG (i.e. via signed commits)

### ISSUE THREAD

**Issue by DinisCruz** [OWASP/owasp-summits#14]
i.e. @devseccon you need to configure your git client to use GPG , note the lack of 'Verified' on your commit. How do I know that that commit was made by you :)

![image](https://cloud.githubusercontent.com/assets/656739/19838158/22c0dd4c-9ec1-11e6-9e01-ca6bd4d60a73.png)

See http://www.slideshare.net/DinisCruz/gpg-signing-git-commits for more details and for instructions on how to set it up

**Comment by FrancoisRaynaud** [comment]
done, closing issue
