### ISSUE TITLE
Add outcome survey screenshots

### ISSUE THREAD

**Issue by Burgess101** [OWASP/owasp-summits#1481]
![survey 1](https://user-images.githubusercontent.com/29351740/27132725-d5ff17ae-5107-11e7-8b33-a3b088319f54.PNG)

![survey 2](https://user-images.githubusercontent.com/29351740/27132732-db1e8d00-5107-11e7-9dec-da753bb6230e.PNG)

**Comment by fzipi** [comment]
@Burgess101 Where is this image goint to be added?

**Comment by Burgess101** [comment]
I have already added them to the session, so no need to worry about it, thanks.
