### ISSUE TITLE
Daily Debrief for monday

### ISSUE THREAD

**Issue by DinisCruz** [OWASP/owasp-summits#1539]
Here it is
[day 1 slides  2.zip](https://github.com/OWASP/owasp-summit-2017/files/1078377/day.1.slides.2.zip)

**Comment by gracerpmg** [comment]
I can't open this file, please resend as a .pdf,
thanks

**Comment by DinisCruz** [comment]
[day 1 slides  2.pdf](https://github.com/OWASP/owasp-summit-2017/files/1078384/day.1.slides.2.pdf)
