### ISSUE TITLE
Formatting outcomes

### ISSUE THREAD

**Issue by Ambg05** [OWASP/owasp-summits#1607]
@DinisCruz , Robert & I are going through the outcomes files to make sure they are all formatted in the same way. Would it be possible to change the style of the file titles from ALL CAPS to Initial Caps Only? We think it would look better & ALL CAPS can seem a bit shouty.  Also the (SUMMIT OUTCOME) text seems unnecessary. If you're happy with this can you let me know how to make those changes please & thanks.
[https://owaspsummit.org/Outcomes/Agile-AppSec/Agile-Practices-for-Security-Teams.html](url)

**Comment by fzipi** [comment]
@Ambg05 , @DinisCruz I've added a #1610 for this, if needed. See screenshots below for comparision.

![screenshot from 2017-06-22 15-18-46](https://user-images.githubusercontent.com/3012076/27449448-d3c38a62-575e-11e7-9d25-7d779bd6762f.png)
![screenshot from 2017-06-22 15-18-21](https://user-images.githubusercontent.com/3012076/27449449-d3c4cd00-575e-11e7-8c0d-de4b1e3cb412.png)
