### ISSUE TITLE
ask gary to have a spot to promote the summit at the conference

### ISSUE THREAD

**Issue by SebaDele** [OWASP/owasp-summits#161]

**Comment by SebaDele** [comment]
requested:
1) can we add a couple of slides to promote the Summit in your conference opening/closing slots and can you mention these? We will obviously provide you the slide(s).
2) would it be possible to get a small slot in the program somewhere during Thursday (I will be at the conference then, have to leave early on Friday) ?
3) Can we add a flyer in the hand-outs?
4) Can we place an A5 page to the appsec conference brochure?

**Comment by SebaDele** [comment]
we can add one slide to the closing remarks
we can add a flyer to the hand-outs (Lisa created a design - will be printed/deliverey with FlyerAlarm)
there is no place anymore to get in the main program
we got a half page ad in the conference brochure (supplied/inserted)

**Comment by FrancoisRaynaud** [comment]
Done
