### ISSUE TITLE
contact participants to register

### ISSUE THREAD

**Issue by SebaDele** [OWASP/owasp-summits#166]

**Comment by NikitaOwasp** [comment]
Hi @SebaDele, I can take this up. I would need the email addresses of the participants. Their names are mentioned in this sheet. https://docs.google.com/spreadsheets/d/1H9D26zIsoUDP6xFV62ONGNRsfAw-SII5zPi76EmVFXw/edit#gid=1889372594

thanks,

**Comment by SebaDele** [comment]
contacted the participants that did not register yet (or indicated that they need sponsoring)
