### ISSUE TITLE
Fix CSS issues on multiple browsers (with new design)

### ISSUE THREAD

**Issue by DinisCruz** [OWASP/owasp-summits#175]

**Comment by akshayowasp** [comment]
CSS issues in Safari Browser:-
1. "BUY TICKET" Button Alignment
2. Text Fonts
![pasted image at 2017_04_07 11_01 pm](https://cloud.githubusercontent.com/assets/26157358/24826229/9d39fdaa-1c4e-11e7-915c-2739208e6db9.png)

**Comment by DinisCruz** [comment]
done by @fzipi
