### ISSUE TITLE
Design search bar and find location for it

### ISSUE THREAD

**Issue by DinisCruz** [OWASP/owasp-summits#185]
At the moment it is at the http://owaspsummit.org/website/summit-organization.html and it doesn't look very good

![image](https://cloud.githubusercontent.com/assets/656739/24829582/6db31c7e-1c6c-11e7-9958-a4ac21f5cb0a.png)

Key questions is:

a) what should the search look like (lisa if you do the design I can implement it)
b) where should we put it

One thing I don't like are the extra adds that google adds to the top of the search results, but I'm already finding the search useful, so I guess we will have to live with it

**Comment by akshayowasp** [comment]
Hey Dinis,
I did some CSS experiment on Search box and it is appearing fine for me with just some changes, please have a look
![image](https://cloud.githubusercontent.com/assets/26157358/24832115/016339a0-1cc6-11e7-8a20-46fbba049c7b.png)

As, search bar have to be on every page we have to put it either on header or footer
- In case of header, we have to add it above our main menu
- In case of footer , it should be below to follow us

**Comment by DinisCruz** [comment]
nice on the CSS
yes maybe by the footer (below follow us)
