### ISSUE TITLE
create co-marketing agreement owasp - devseccon

### ISSUE THREAD

**Issue by SebaDele** [OWASP/owasp-summits#29]
check with laura for template
add in the mutual agreements
sign

**Comment by DinisCruz** [comment]
can we post the agreement text here?

**Comment by DinisCruz** [comment]
Do we still need this?

**Comment by FrancoisRaynaud** [comment]
Would be good to go back to the board on the changes we agreed to seek their support again.

Francois

**Comment by DinisCruz** [comment]
ok, I was also thinking that what we also need them to support is the use of OWASP employees time to help with the Summit. 

@SebaDele

**Comment by DinisCruz** [comment]
Closing this since this seems to be sorted
