### ISSUE TITLE
Francois to join OWASP slack channel 

### ISSUE THREAD

**Issue by DinisCruz** [OWASP/owasp-summits#3]
https://owasp.slack.com/archives/owasp-dsc-summit/

**Comment by FrancoisRaynaud** [comment]
did you invite francois@devseccon.com?

**Comment by FrancoisRaynaud** [comment]
dinis: could you resend the invite please? i haven't received it

**Comment by DinisCruz** [comment]
try this http://blog.diniscruz.com/2016/06/link-to-join-owasp-slack.html

**Comment by FrancoisRaynaud** [comment]
sorted

**Comment by FrancoisRaynaud** [comment]
sorted

**Comment by FrancoisRaynaud** [comment]
sorted
