### ISSUE TITLE
start using the OwaspSummit twitter account

### ISSUE THREAD

**Issue by DinisCruz** [OWASP/owasp-summits#39]
https://twitter.com/owaspsummit was mainly used on the last Summit

Who controls this account?

![image](https://cloud.githubusercontent.com/assets/656739/21581755/0c9474fa-d037-11e6-890c-a454347ea5e6.png)

**Comment by bkimminich** [comment]
I asked staff about who has access to this. Will post credentials here once I have them. 




... 

Just kidding! 😈

**Comment by DinisCruz** [comment]
:)

Would be interesting to see how long until it went defaced :)

**Comment by bkimminich** [comment]
OWASP community manager has now access to the account. I guess this solves this issue?

**Comment by DinisCruz** [comment]
@SebaDele as far as I can tell we are still waiting for it right?

**Comment by SebaDele** [comment]
No, we now have access to it

**Comment by SebaDele** [comment]
core team now has access to this
