### ISSUE TITLE
Audio for Cross company hackathon

### ISSUE THREAD

**Issue by DinisCruz** [OWASP/owasp-summits#589]
http://owaspsummit.org/Working-Sessions/Security-Crowdsourcing/Cross-Company-Hackathons.html
[Cross-Company-hackathons.mp3.zip](https://github.com/OWASP/owasp-summit-2017/files/1033607/Cross-Company-hackathons.mp3.zip)

Hi @Ambg05 can you try to make sense of this audio and convert it into a Working Session description?

**Comment by Ambg05** [comment]
Hi, I just created a PR for this file #593.
Let me know if you're happy with what I did.  The audio quality was fine, it just takes me a little longer to transcribe & check that I've got everything. I'll get to the other files tomorrow or on Monday.

**Comment by DinisCruz** [comment]
It looked great :)

Thanks

**Comment by DinisCruz** [comment]
@Ambg05 can you change it a little bit to make it clear that this is supposed to happen between companies.

I believe it shows in the title, but it is not clear in the text

**Comment by Ambg05** [comment]
Hi @DinisCruz

Just to clarify my own understanding of a cross company hackathon: do you mean that one company that has new products etc. will invite other companies to try and hack the new products? So it is an inter-company hackathon rather than an intra-company hackathon?

Thanks.

**Comment by DinisCruz** [comment]
yes it is a multi-company agreement where they organise events where participants (from security team and developers) from both companies (two or more) 
The idea of doing this for new products is that it is more realistic with the flow of development in companies, and provides a new fresh target for tests

@ante-gulam can you share some of you views? (as you can see by this thread you can do it with audio)
