### ISSUE TITLE
Audio for 'Internal Bug Bounty Programs'

### ISSUE THREAD

**Issue by DinisCruz** [OWASP/owasp-summits#590]
http://owaspsummit.org/Working-Sessions/Security-Crowdsourcing/Internal-Bug-Bounties-Programmes.html

[Internal Bug bounty programs.mp3.zip](https://github.com/OWASP/owasp-summit-2017/files/1033615/Internal.Bug.bounty.programs.mp3.zip)

@Ambg05 here is another one

**Comment by Ambg05** [comment]
Done.

**Comment by Ambg05** [comment]
@DinisCruz  I don't seem to be authorised to close these issues! Or am I missing something . . .

**Comment by DinisCruz** [comment]
ahh maybe you can't with your current level of access
