### ISSUE TITLE
Audio for 'Security Crowdsourcing the SDL Practices'

### ISSUE THREAD

**Issue by DinisCruz** [OWASP/owasp-summits#592]
http://owaspsummit.org/Working-Sessions/Security-Crowdsourcing/Security-Crowdsourcing-the-SDL-Practices.html

[Security Crowdsourcing the SDL Practices.mp3.zip](https://github.com/OWASP/owasp-summit-2017/files/1033630/Security.Crowdsourcing.the.SDL.Practices.mp3.zip)

One more @Ambg05

**Comment by DinisCruz** [comment]
@Ambg05 can you look at the content that is already at http://owaspsummit.org/Working-Sessions/Security-Crowdsourcing/Crowdsourcing-Security-Knowledge.html since we might be able to merge these two Working Sessions

**Comment by Ambg05** [comment]
@DinisCruz  I've merged the audio in with http://owaspsummit.org/Working-Sessions/Security-Crowdsourcing/Crowdsourcing-Security-Knowledge.html at PR #611 

Let me know if you're happy with what I've done.

**Comment by DinisCruz** [comment]
Hi @Ambg05 for issues like this
 - can you add the comment in thePR
 - can you close the issue once the audio is done and the text is the PR

thx

great stuff and good to see that we workflow works
