### ISSUE TITLE
Lanyrd page

### ISSUE THREAD

**Issue by bkimminich** [OWASP/owasp-summits#61]
http://lanyrd.com/2017/owaspsummit

* [x] Event created on Lanyrd 
* [x] Venue created on Lanyrd
* [x] Added Twitter handle and official hashtag #owaspsummit
* [ ] Add workshop schedule (workshop organizers might be set up as "speakers"?)
* [ ] _add subtasks here_

**Comment by DinisCruz** [comment]
very cool, thanks

![image](https://cloud.githubusercontent.com/assets/656739/22978344/4c7aeb5a-f38a-11e6-8cea-69a875c1684d.png)

**Comment by DinisCruz** [comment]
note: the final workshop schedule will only be ready in May (early June), so all we will have until then are the Workshops titles and their popularity
