### ISSUE TITLE
Catering - venue and/or own?

### ISSUE THREAD

**Issue by NikitaOwasp** [OWASP/owasp-summits#781]

**Comment by FrancoisRaynaud** [comment]
All 5-day tickets with accommodation includes Breakfast, Lunch and Dinner.
All day tickets include Lunch.

**Comment by SebaDele** [comment]
got a number of proposals - need to decide by Tuesday 6

**Comment by jemmads** [comment]
All times spent in the venue will be catered for by the venue. Food orders will be placed through Tesco for food at the villas
