### ISSUE TITLE
Question: Do we need a mailing list?

### ISSUE THREAD

**Issue by DinisCruz** [OWASP/owasp-summits#8]
I'm starting to think that between GitHub pages, GitHub issues, Slack and Twitter we have a good way to communicate 

What do you think?

**Comment by FrancoisRaynaud** [comment]
Agreed, maybe even too many, although as long as they Integrate it's fine. 
The mailing list can be used later on for all attendees to repeat the info present on GitHub, etc...

**Comment by DinisCruz** [comment]
ok closing issue
