### ISSUE TITLE
Improve SEO of owaspsummit.org website

### ISSUE THREAD

**Issue by DinisCruz** [OWASP/owasp-summits#84]
At the moment it doesn't show up on Google searches

![image](https://cloud.githubusercontent.com/assets/656739/23333467/81819f5a-fb83-11e6-85a4-ae62bf9f1ed1.png)

I think one of the solutions will be to submit the http://owaspsummit.org site to google

**Comment by FrancoisRaynaud** [comment]
http://owaspsummit.org submitted to google for indexing

**Comment by DinisCruz** [comment]
Closing since this is now operational 

We are currently at position number 7

![image](https://cloud.githubusercontent.com/assets/656739/23672229/e96074e0-0365-11e7-97e1-47884a5cfdf2.png)
