### ISSUE TITLE
Create twitter account dedicated for Summit

### ISSUE THREAD

**Issue by DinisCruz** [OWASP/owasp-summits#9]
What should it be called? 
- **OWASP-DevSecCon**
- **OWASP-DevSecCon-Summit** (this feels to big)
- **OWASP-DSC-Summit** (this loses the DevSec reference)

Tasks:
- [x] Create twitter account
- [x] Add links to home page

**Comment by FrancoisRaynaud** [comment]
That works and still available 😄

**Comment by FrancoisRaynaud** [comment]
this one is good: OWASP-DevSecCon

**Comment by DinisCruz** [comment]
ok can you create it?

**Comment by DinisCruz** [comment]
and close this issue when done (after updating the README page)

:)

**Comment by FrancoisRaynaud** [comment]
Done. @OWASPDevSecCon
I'll update the task and share details tomorrow morning.
