### ISSUE TITLE
get photographer for pictures

### ISSUE THREAD

**Issue by SebaDele** [OWASP/owasp-summits#908]

**Comment by jemmads** [comment]
@JemmaButtle can you look into local photographers, please?

**Comment by JemmaButtle** [comment]
Jemma B:

Hi Jemma

Thank you for your email, we are able to cover the event as we are a small team here.

Photography and Video filming
Edit and release all still images high and low resolution versions with full copyright release
£3200.00 + Vat

There would be an additional charge for the video edit which depends on your final requirements. I would estimate this to be approximately £300-£800 + Vat depending on how detailed and creative it needs to be.

We are a reliable company established for over 20 years and provide a thoroughly professional service.

Kind regards

Kam

**Comment by SebaDele** [comment]
ask participants to cover this
