### ISSUE TITLE
Invited + participating = Duplicate schedule entries

### ISSUE THREAD

**Issue by bkimminich** [OWASP/owasp-summits#941]
It's kind of what you'd expect to happen, but if it's possible here's a fix proposal:
- participating only = show as "participating"
- invited only = show as" invited" plus 🎫 symbol
- both = show as "participating" plus 🎫 symbol

**Comment by DinisCruz** [comment]
or, just fix it on the actually that has that mapping :)

the latest version colour codes these (which will make it more obvious)

For example here is your personalised schedule

![image](https://user-images.githubusercontent.com/656739/26856579-68ae6a1a-4b1c-11e7-9ec7-18b0ce24a35a.png)

**Comment by fzipi** [comment]
I think this could be closed.
