### ISSUE TITLE
Finalise the Amazon order

### ISSUE THREAD

**Issue by DinisCruz** [OWASP/owasp-summits#988]
Here is the current first pass of the order https://www.amazon.co.uk/gp/registry/wishlist/2Z8X8G7DAUON0/ref=cm_wl_list_o_4?

![image](https://user-images.githubusercontent.com/656739/26888220-3cf3143a-4ba2-11e7-9d17-2bc5fc2c029c.png)

**Comment by jemmads** [comment]
Liaising with AV contact to scope requirements

**Comment by jemmads** [comment]
Awaiting quote from Concept Events before finalising Amazon list

**Comment by jemmads** [comment]
To be added:
https://www.amazon.co.uk/Durable-145602-Badgemaker-Printable-Insert/dp/B001IVILUQ/ref=sr_1_1?ie=UTF8&qid=1496995241&sr=8-1&keywords=durable+60+x+90 
and corresponding pouches

**Comment by jemmads** [comment]
Emailed to Tiffany, Kate and Claudia to place the order

**Comment by mtesauro** [comment]
Just sent you an email this - its not possible with the time constraints.  Full details in my reply to your request.  You'll need to source these locally and get reimbursed.

**Comment by DinisCruz** [comment]
Hi Matt , can you send that email to me too? 

Btw, Jemma did not received the Owasp email account details, where did you sent it too? (which means that she has also not read that email)

**Comment by mtesauro** [comment]
Email went to a bunch of people...

---------- Forwarded message ----------
From: Matt Tesauro <matt.tesauro@owasp.org>
Date: Fri, Jun 9, 2017 at 3:05 PM
Subject: Fwd: Amazon Order
To: jemma@je[redacted].co.uk
Cc: Tiffany Long <tiffany.long@o[redacted].org>, Kate Hartmann <kate.hartmann@o[redacted].org>, Claudia Casanovas <Claudia.Aviles-Casanovas@o[redacted].org>, dinis cruz <dinis.cruz@o[redacted].org>, Seba <seba@o[redacted].org>

**Comment by DinisCruz** [comment]
Great just saw it, man what a mess from Amazon

Well you tried hard, can't ask for more

We'll do the order from here

**Comment by jemmads** [comment]
Road trip to be organised when the relevant people are on site. Staples/Office Outlet in Milton Keynes is the only option at these stage
