### ISSUE TITLE
Contact Venue AV company

### ISSUE THREAD

**Issue by DinisCruz** [OWASP/owasp-summits#989]
Dinis to introduce Jemma to CP contact

**Comment by jemmads** [comment]
Spoken with Anna Forrester this morning around tech support and AV for venue

**Comment by jemmads** [comment]
Quote provided to Dinis

**Comment by jemmads** [comment]
Quote authorised by @DinisCruz. AV team will be at the venue on Sunday. All borrowed laptops need to be available and in the venue by 1pm to run tech tests
